"""add_chat_threads_and_messages_tables

Revision ID: 175419da5d5b
Revises: d2e3f4g5h6i7
Create Date: 2026-01-04 14:26:22.249577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '175419da5d5b'
down_revision: Union[str, None] = 'd2e3f4g5h6i7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    table_names = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    # Create chat_threads table if it doesn't exist
    if 'chat_threads' not in table_names:
        op.create_table('chat_threads',
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column('archived', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('space_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('chat_threads', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_chat_threads_title'), ['title'], unique=False)
            batch_op.create_index(batch_op.f('ix_chat_threads_updated_at'), ['updated_at'], unique=False)

    # Create chat_messages table if it doesn't exist
    if 'chat_messages' not in table_names:
        op.create_table('chat_messages',
        sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatmessagerole'), nullable=False),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('thread_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('chat_messages', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_chat_messages_thread_id'), ['thread_id'], unique=False)

    # SQLite doesn't support altering column types easily
    # For development with SQLite, we skip the type changes
    # For production PostgreSQL, these changes would be applied
    if conn.dialect.name != 'sqlite':
        with op.batch_alter_table('connectors', schema=None) as batch_op:
            batch_op.alter_column('user_id',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Uuid(),
                   existing_nullable=False)

        if 'data_exchange' in table_names:
            with op.batch_alter_table('data_exchange', schema=None) as batch_op:
                batch_op.alter_column('transaction_id',
                       existing_type=sa.VARCHAR(),
                       type_=sa.Uuid(),
                       existing_nullable=False)
                batch_op.alter_column('id',
                       existing_type=sa.VARCHAR(),
                       type_=sa.Uuid(),
                       existing_nullable=False)
                batch_op.drop_index(batch_op.f('ix_data_exchange_timestamp'))

        if 'datasource' in table_names:
            with op.batch_alter_table('datasource', schema=None) as batch_op:
                batch_op.alter_column('id',
                       existing_type=sa.NUMERIC(),
                       type_=sa.Uuid(),
                       existing_nullable=False)

        with op.batch_alter_table('documents', schema=None) as batch_op:
            batch_op.alter_column('user_id',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Uuid(),
                   existing_nullable=False)

        if 'flow_execution_task' in table_names:
            with op.batch_alter_table('flow_execution_task', schema=None) as batch_op:
                batch_op.alter_column('flow_id',
                       existing_type=sa.VARCHAR(),
                       type_=sa.Uuid(),
                       existing_nullable=False)
                batch_op.alter_column('user_id',
                       existing_type=sa.VARCHAR(),
                       type_=sa.Uuid(),
                       existing_nullable=True)
                batch_op.alter_column('id',
                       existing_type=sa.VARCHAR(),
                       type_=sa.Uuid(),
                       existing_nullable=False)

        with op.batch_alter_table('podcasts', schema=None) as batch_op:
            batch_op.alter_column('user_id',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Uuid(),
                   existing_nullable=False)

        with op.batch_alter_table('space_invites', schema=None) as batch_op:
            batch_op.alter_column('inviter_id',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Uuid(),
                   existing_nullable=False)

        with op.batch_alter_table('space_memberships', schema=None) as batch_op:
            batch_op.alter_column('user_id',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Uuid(),
                   existing_nullable=False)

        with op.batch_alter_table('spaces', schema=None) as batch_op:
            batch_op.alter_column('user_id',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Uuid(),
                   existing_nullable=False)

    # Fix index changes (these work on SQLite)
    with op.batch_alter_table('documents', schema=None) as batch_op:
        try:
            # For SQLite, just drop and recreate the index without constraint operations
            batch_op.drop_index('ix_documents_unique_identifier_hash')
        except Exception:
            pass  # Index might not exist
        batch_op.create_index('ix_documents_unique_identifier_hash', ['unique_identifier_hash'], unique=True)

    with op.batch_alter_table('space_invites', schema=None) as batch_op:
        try:
            batch_op.drop_index('ix_space_invites_token')
        except Exception:
            pass  # Index might not exist
        batch_op.create_index('ix_space_invites_token', ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('space_memberships', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('space_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_space_invites_token'))
        batch_op.create_index(batch_op.f('ix_space_invites_token'), ['token'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_space_invites_token'), ['token'])
        batch_op.alter_column('inviter_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('flow_execution_task', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('flow_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_unique_identifier_hash')
        batch_op.create_index('ix_documents_unique_identifier_hash', ['unique_identifier_hash'], unique=False)
        # For SQLite, recreating unique index is sufficient (no need for separate constraint)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('datasource', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('data_exchange', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_exchange_timestamp'), ['timestamp'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('transaction_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_thread_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_threads_updated_at'))
        batch_op.drop_index(batch_op.f('ix_chat_threads_title'))

    op.drop_table('chat_threads')
    # ### end Alembic commands ###
