"""sync models with phase 1-7 changes

Revision ID: 4ba9e0ce9edf
Revises: i7j8k9l0m1n2
Create Date: 2026-01-23 15:10:08.601772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '4ba9e0ce9edf'
down_revision: Union[str, None] = 'i7j8k9l0m1n2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    is_sqlite = conn.dialect.name == 'sqlite'

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        # TSVECTOR and VECTOR are PostgreSQL-specific, skip for SQLite
        if not is_sqlite:
            batch_op.add_column(sa.Column('tsvector', postgresql.TSVECTOR(), nullable=True))
            batch_op.alter_column('embedding',
                   existing_type=sqlite.JSON(),
                   type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
                   existing_nullable=True)

    # Index operations work for both SQLite and PostgreSQL
    inspector = Inspector.from_engine(conn)
    connectors_indexes = inspector.get_indexes('connectors')
    if any(idx['name'] == 'idx_connector_data_construction_folder_id' for idx in connectors_indexes):
        with op.batch_alter_table('connectors', schema=None) as batch_op:
            batch_op.drop_index('idx_connector_data_construction_folder_id')

    data_exchange_indexes = inspector.get_indexes('data_exchange')
    if any(idx['name'] == 'ix_data_exchange_timestamp' for idx in data_exchange_indexes):
        with op.batch_alter_table('data_exchange', schema=None) as batch_op:
            batch_op.drop_index('ix_data_exchange_timestamp')

    with op.batch_alter_table('datasource', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        # VECTOR is PostgreSQL-specific, skip for SQLite
        if not is_sqlite:
            batch_op.alter_column('embedding',
                   existing_type=sqlite.JSON(),
                   type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
                   existing_nullable=True)

        # Index operations work for both SQLite and PostgreSQL
        documents_indexes = inspector.get_indexes('documents')
        if any(idx['name'] == 'idx_document_data_construction_file_id' for idx in documents_indexes):
            batch_op.drop_index('idx_document_data_construction_file_id')
        if any(idx['name'] == 'idx_document_data_construction_folder_id' for idx in documents_indexes):
            batch_op.drop_index('idx_document_data_construction_folder_id')
        if any(idx['name'] == 'idx_document_processing_status' for idx in documents_indexes):
            batch_op.drop_index('idx_document_processing_status')
        batch_op.create_index(batch_op.f('ix_documents_data_construction_file_id'), ['data_construction_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_data_construction_folder_id'), ['data_construction_folder_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    is_sqlite = conn.dialect.name == 'sqlite'
    inspector = Inspector.from_engine(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        documents_indexes = inspector.get_indexes('documents')
        if any(idx['name'] == 'ix_documents_data_construction_folder_id' for idx in documents_indexes):
            batch_op.drop_index(batch_op.f('ix_documents_data_construction_folder_id'))
        if any(idx['name'] == 'ix_documents_data_construction_file_id' for idx in documents_indexes):
            batch_op.drop_index(batch_op.f('ix_documents_data_construction_file_id'))
        batch_op.create_index(batch_op.f('idx_document_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_document_data_construction_folder_id'), ['data_construction_folder_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_document_data_construction_file_id'), ['data_construction_file_id'], unique=False)

        # VECTOR is PostgreSQL-specific, skip for SQLite
        if not is_sqlite:
            batch_op.alter_column('embedding',
                   existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
                   type_=sqlite.JSON(),
                   existing_nullable=True)

    with op.batch_alter_table('datasource', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('data_exchange', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_exchange_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_connector_data_construction_folder_id'), ['data_construction_folder_id'], unique=False)

    with op.batch_alter_table('chunks', schema=None) as batch_op:
        # TSVECTOR and VECTOR are PostgreSQL-specific, skip for SQLite
        if not is_sqlite:
            batch_op.alter_column('embedding',
                   existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
                   type_=sqlite.JSON(),
                   existing_nullable=True)
            batch_op.drop_column('tsvector')

    # ### end Alembic commands ###
