"""add connector indexing fields

Revision ID: bc8d5b8da775
Revises: 4ba9e0ce9edf
Create Date: 2026-01-23 15:26:55.001181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'bc8d5b8da775'
down_revision: Union[str, None] = '4ba9e0ce9edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist before adding them
    connectors_columns = {col['name'] for col in inspector.get_columns('connectors')}

    with op.batch_alter_table('connectors', schema=None) as batch_op:
        if 'data_construction_folder_id' not in connectors_columns:
            batch_op.add_column(sa.Column('data_construction_folder_id', sa.Integer(), nullable=True))

        if 'indexing_status' not in connectors_columns:
            batch_op.add_column(sa.Column('indexing_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='idle'))

        if 'indexed_file_count' not in connectors_columns:
            batch_op.add_column(sa.Column('indexed_file_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    connectors_columns = {col['name'] for col in inspector.get_columns('connectors')}

    with op.batch_alter_table('connectors', schema=None) as batch_op:
        if 'indexed_file_count' in connectors_columns:
            batch_op.drop_column('indexed_file_count')

        if 'indexing_status' in connectors_columns:
            batch_op.drop_column('indexing_status')

        if 'data_construction_folder_id' in connectors_columns:
            batch_op.drop_column('data_construction_folder_id')

    # ### end Alembic commands ###
