"""add_entity_and_relation_tables

Revision ID: e3f4g5h6i7j8
Revises: 175419da5d5b
Create Date: 2026-01-04 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'e3f4g5h6i7j8'
down_revision: Union[str, None] = '175419da5d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create entity table
    op.create_table('entity',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column('aliases', sa.JSON(), nullable=True),
        sa.Column('embedding', sa.JSON(), nullable=True),
        sa.Column('properties', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('space_id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=True),
        sa.Column('chunk_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_space_id'), ['space_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_chunk_id'), ['chunk_id'], unique=False)

    # Create relation table
    op.create_table('relation',
        sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column('weight', sa.Float(), nullable=False),
        sa.Column('properties', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('space_id', sa.Integer(), nullable=False),
        sa.Column('source_entity_id', sa.Integer(), nullable=False),
        sa.Column('target_entity_id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=True),
        sa.Column('chunk_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_entity_id'], ['entity.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_entity_id'], ['entity.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relation_relation_type'), ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_relation_space_id'), ['space_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relation_source_entity_id'), ['source_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relation_target_entity_id'), ['target_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relation_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relation_chunk_id'), ['chunk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relation_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_relation_document_id'))
        batch_op.drop_index(batch_op.f('ix_relation_target_entity_id'))
        batch_op.drop_index(batch_op.f('ix_relation_source_entity_id'))
        batch_op.drop_index(batch_op.f('ix_relation_space_id'))
        batch_op.drop_index(batch_op.f('ix_relation_relation_type'))

    op.drop_table('relation')

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_entity_document_id'))
        batch_op.drop_index(batch_op.f('ix_entity_space_id'))
        batch_op.drop_index(batch_op.f('ix_entity_entity_type'))
        batch_op.drop_index(batch_op.f('ix_entity_name'))

    op.drop_table('entity')
    # ### end Alembic commands ###
