"""add_knowledge_graph_fields_to_space

Revision ID: f4g5h6i7j8k9
Revises: e3f4g5h6i7j8
Create Date: 2026-01-04 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'f4g5h6i7j8k9'
down_revision: Union[str, None] = 'e3f4g5h6i7j8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Check if the columns already exist
    columns = [col['name'] for col in inspector.get_columns('spaces')]

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        # Add enable_knowledge_graph column if it doesn't exist
        if 'enable_knowledge_graph' not in columns:
            batch_op.add_column(sa.Column('enable_knowledge_graph', sa.Boolean(), nullable=False, server_default='0'))

        # Add auto_entity_extraction column if it doesn't exist
        if 'auto_entity_extraction' not in columns:
            batch_op.add_column(sa.Column('auto_entity_extraction', sa.Boolean(), nullable=False, server_default='1'))

        # Add graph_llm_id column if it doesn't exist
        if 'graph_llm_id' not in columns:
            batch_op.add_column(sa.Column('graph_llm_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_column('graph_llm_id')
        batch_op.drop_column('auto_entity_extraction')
        batch_op.drop_column('enable_knowledge_graph')
    # ### end Alembic commands ###
